# Site settings
title: Walter Bolitto Carvalho
description: |
  Educador e desenvolvedor de jogos de São Paulo

url: https://bolitto.github.io/bbolitto.github.io

about_title: Sobre
projects_title: Página Inicial

# User settings
user_description_appendix: |

## Tracker
google_analytics_id: UA-133311202-1

email: bolitto.walter@gmail.com
linkedin: walter-bolitto-carvalho-851290120
github: bolitto
#angellist: rassaby

relevant_tags: ['jogos', 'cursos', 'outros']

resume_url: https://bolitto.github.io/cv/

author: Walter Bolitto Carvalho
author_title: 
author_photo: IMG-20210624-WA0001.jpg
user_description_short: |
  Sou educador e desenvolvedor de jogos e moro em São Paulo.
  Tenho experiência com game design, tecnologias para educação e campanhas, comunicação digital e análise de dados.

  Sou pós-graduado em Educação e Tecnologia pela Universidade Federal de São Carlos, crio jogos digitais e de tabuleiro com temáticas sociais, educacionais e voltadas à divulgação científica.

keywords: 'bolitto,walter bolitto,walter bolitto carvalho,educação,board games,jogos,educação e tecnologia'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/sobre'


plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
